### ISSUE TITLE
Bundle language versions of forms into one json-file

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/fhir-tools#125]
When creating new forms on several languages in Structor, they are bundled into one json file that contains all languages. The forms created in excel are not bundled, there is one json-file for each language. 

E.g. a form created in Excel is on 4 languages, they are now 4 json files. When uploading one of them into Structor, you only see that one language, it is not connected to the other language versions of that form. 

We need a way to bundle the "old" forms so that there is only one json-file that contain all languages.

**Comment by kennethmyhra** [comment]
Fixed by #141
